# Generated by Django 4.2.7 on 2023-12-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema_rejiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='rejiser',
        ),
    ]
